# Makefile for running unit tests
#

BASH=bash
PYTHON=python
SP3=sp3

all: unit_scripts

unit_scripts:
	$(BASH) sp3_config_1
	$(BASH) sp3_basic_1
	$(BASH) sp3_basic_2

utests:
	$(PYTHON) access_1.py
	$(PYTHON) access_2.py
	$(PYTHON) access_3.py
