#!/bin/bash

DEBUG=0
if [ $# -gt 0 ]; then

		if [ $1 == "-d" ]; then
				DEBUG=1
				echo "Debug Mode"
				export MINIO_HTTP_TRACE=minio.log
		fi
fi

MBIN=`which minio`
if [ -z $MBIN ]; then
	echo "minio not found"
	exit
fi

DATA_DIR=~/mdata
mkdir -p ${DATA_DIR}

# Update minio first to make sure we are current
#minio update

minio --quiet server ${DATA_DIR}


