#!/bin/bash

sp3 -r --gend ixl://stuff/tdata
sp3 -r --copy ixl://stuff/tdata/ minio://nabinix/tdata/
sp3 -r --delete ixl://stuff/tdata/
sp3 -r --delete minio://nabinix/tdata/
sp3 -r --gend minio://nabinix/tdata
sp3 -r --delete minio://nabinix/tdata/

exit
#
sp3 --get minio://nabinix/index.html ixl://stuff/index.html
sp3 --delete minio://nabinix/index.html
sp3 --delete ixl://stuff/index.html

