#!/usr/bin/env python
""" S3 access for data """
import sys
import os

from os import path
from os.path import expanduser

import argparse
import asyncio
import logzero

from logzero import logger
from logzero import logging


from edgex_access import EdgexConfig
from edgex_access import EdgexDataAccess

DEFAULT_CONFIG = "/.sp3"
SAMPLE_CONFIG = ' \
{ \
	"stores" : [ \
	{ \
		"NAME" : "edgex", \
		"STORE_TYPE" :"S3", \
		"ACCESS" : "", \
		"SECRET" : "", \
		"REGION" : "", \
		"ENDPOINT" : "https://edge.nexenta.com", \
		"TOKEN" : "", \
		"SSL" : "False", \
		"BUCKET" : "", \
		"TAG" : "edgex" \
	}, \
	{ \
		"NAME" : "ix", \
		"STORE_TYPE" :"FS", \
		"TOKEN" : "", \
		"BUCKET" : "/Users/sample.user/Workspace", \
		"TAG" : "ix"  \
	} \
	], \
	"PRIMARY" : "edgex", \
	"SYNCIO" : "QUEUED", \
	"DEBUG" : 5, \
    "DATATEST" : "data/", \
    "META" : "meta/" \
} \
'





def copy_usage():
    logger.info("copy <source> <dest>")
    logger.info("e.g.\t % sd3 --copy aws3://mbucket/file1 minio://obucket/file1")

def copy_cmd(cfg, loop, args, r):
    if len(args) < 2:
        copy_usage()
        return
    source_obj = args[0]
    dest_obj = args[1]
    logger.info("copy\t" + source_obj +"\t" + dest_obj)
    try:
        eda = EdgexDataAccess(cfg, loop)
        eda.create_task('copy', source_obj, dest_obj, r)
        eda.execute(loop)
    except Exception as exp:
        logger.exception(exp)

def move_usage():
    logger.info("move <source> <dest>")
    logger.info("e.g.\t % sd3 --move aws3://mbucket/file1 minio://obucket/file1")

def move_cmd(cfg, loop, args, r):
    if len(args) < 2:
        move_usage()
        return
    source_obj = args[0]
    dest_obj = args[1]
    logger.info("move\t" + source_obj +"\t" + dest_obj)
    try:
        eda = EdgexDataAccess(cfg, loop)
        eda.create_task('move', source_obj, dest_obj, r)
        eda.execute(loop)
    except Exception as exp:
        logger.exception(exp)

def delete_usage():
    logger.info("delete <dest>")
    logger.info("e.g.\t % sd3 --delete aws3://mbucket/file1")


def delete_cmd(cfg, loop, args, r):
    if len(args) < 1:
        delete_usage()
        return
    dest_obj = args[0]
    logger.info("delete\t" + dest_obj)
    try:
        eda = EdgexDataAccess(cfg, loop)
        eda.create_task('delete', "", dest_obj, r)
        eda.execute(loop)
    except Exception as exp:
        logger.exception(exp)
    
def wget_usage():
    logger.info("wget <url>")
    logger.info("e.g.\t % sd3 --wget http://google.com/file1")

def wget_cmd(cfg, loop, args, r):
    if len(args) < 1:
        wget_usage()
        return
    dest_obj = args[0]
    logger.info("wget\t" + dest_obj)
    try:
        eda = EdgexDataAccess(cfg, loop)
        eda.create_task('wget', "", dest_obj, r)
        eda.execute(loop)
    except Exception as exp:
        logger.exception(exp)

def config_usage():
    logger.info(sys.argv[0] + "\t--config  [ <ls> <add> <del> ] ...")

def config_cmd(cfg, loop, args, r):
    """ commands to configure the utility with the json config """
    if len(args) < 1:
        config_usage()
        return
    try:
        if args[0] == "ls":
            cfg.show_all()
        elif args[0] == "add":
            pass
        elif args[0] == "del":
            pass
        else:
            config_usage()
    except Exception as exp:
        logger.exception(exp)

def store_usage():
    logger.info(sys.argv[0] +"\t [ <ls> <add> <del> ] .....")

def store_cmd(cfg, loop, args, r):
    if len(args) < 1:
        store_usage()
        return
    try:
        if args[0] == "ls":
            cfg.show_stores()
        elif args[0] == "add":
            pass
        elif args[0] == "del":
            pass
        else:
            store_usage()
    except Exception as exp:
        logger.exception(exp)

def meta_usage():
    logger.info(sys.argv[0] + "\t [ <ls> <add> <del> ] ...")

def meta_cmd(cfg, loop, args, r):
    if len(args) < 1:
        meta_usage()
        return
    try:
        if args[0] == "ls":
            pass
        elif args[0] == "add":
            pass
        elif args[0] == "del":
            pass
        else:
            meta_usage()
    except Exception as exp:
        logger.exception(exp)

def ls_usage():
    logger.info(sys.argv[0] + "\t ls \t [ store://folder/.../object ]")

def ls_cmd(cfg, loop, args, r):
    if len(args) < 1:
        ls_usage()
        return
    dest_obj = args[0]
    logger.info("ls\t" + dest_obj)
    try:
        eda = EdgexDataAccess(cfg, loop)
        eda.create_task('ls', dest_obj, "", r)
        eda.execute(loop)
    except Exception as exp:
        logger.exception(exp)

def info_usage():
    logger.info(sys.argv[0] + "\t info \t [ store://folder/.../object ]")

def info_cmd(cfg, loop, args, r):
    if len(args) < 1:
        info_usage()
        return
    dest_obj = args[0]
    logger.info("info\t" + dest_obj)
    try:
        eda = EdgexDataAccess(cfg, loop)
        eda.create_task('info', dest_obj, "", r)
        eda.execute(loop)
    except Exception as exp:
        logger.exception(exp)

def exists_usage():
    logger.info(sys.argv[0] + "\t exists \t [ store://folder/.../object ]")

def exists_cmd(cfg, loop, args, r):
    if len(args) < 1:
        exists_usage()
        return
    dest_obj = args[0]
    logger.info("exists\t" + dest_obj)
    try:
        eda = EdgexDataAccess(cfg, loop)
        eda.create_task('exists', dest_obj, "", r)
        eda.execute(loop)
    except Exception as exp:
        logger.exception(exp)

def get_usage():
    logger.info(sys.argv[0] + "\t get \t[ store1://folder/.../object ] [ store2://folderX/obj2] ")

def get_cmd(cfg, loop, args, r):
    if len(args) < 2:
        get_usage()
        return
    source_obj = args[0]
    dest_obj = args[1]
    logger.info("get\t" + source_obj +"\t" + dest_obj)
    try:
        eda = EdgexDataAccess(cfg, loop)
        eda.create_task('get', source_obj, dest_obj, r)
        eda.execute(loop)
    except Exception as exp:
        logger.exception(exp)

def put_usage():
    logger.info(sys.argv[0] + "\t put \t[ store://folder/.../object ] [ store2://folderX/obj2] ")

def put_cmd(cfg, loop, args, r):
    if len(args) < 2:
        put_usage()
        return
    source_obj = args[0]
    dest_obj = args[1]
    logger.info("put\t" + source_obj +"\t" + dest_obj)
    try:
        eda = EdgexDataAccess(cfg, loop)
        eda.create_task('put', source_obj, dest_obj, r)
        eda.execute(loop)
    except Exception as exp:
        logger.exception(exp)

def command(cmd, cfg, loop, args, r):

    if cmd == "copy":
        copy_cmd(cfg, loop, args, r)
    elif cmd == "move":
        move_cmd(cfg, loop, args, r)
    elif cmd == "delete":
        delete_cmd(cfg, loop, args, r)
    elif cmd == "wget":
        wget_cmd(cfg, loop, args, r)
    elif cmd == "config":
        config_cmd(cfg, loop, args, r)
    elif cmd == "store":
        store_cmd(cfg, loop, args, r)
    elif cmd == "meta":
        meta_cmd(cfg, loop, args, r)
    elif cmd == "ls":
        ls_cmd(cfg, loop, args, r)
    elif cmd == "get":
        get_cmd(cfg, loop, args, r)
    elif cmd == "ls":
        put_cmd(cfg, loop, args, r)
    elif cmd == "info":
        info_cmd(cfg, loop, args, r)
    elif cmd == "exists":
        exists_cmd(cfg, loop, args, r)
    else:
        logger.error("Unknown Command " + cmd)

    loop.close()


def main():

    # TODO: location of edgex_access directory for the package
    HERE = path.abspath(path.dirname(__file__))
    VPATH = os.path.join(HERE, '../edgex_access', 'version.py')
    __version__ = eval(open(VPATH).read())


    parser = argparse.ArgumentParser(
        description="S3/Posix data ls/put/get/delete/copy/move",
                    epilog="Manage data the same way on all data store platforms")

    parser.add_argument('-d', '--debug', type=int, help='debug value', required=False)
    parser.add_argument('-r', action='store_true', help='recursive run')
    parser.add_argument('--version', action='version', version=__version__)

    parser.add_argument("--ls", help="Listing of this object or folder", nargs=argparse.REMAINDER)
    parser.add_argument("--exists", help="Listing of this object or folder", nargs=argparse.REMAINDER)
    parser.add_argument("--info", help="Listing of this object or folder", nargs=argparse.REMAINDER)
    parser.add_argument("--put", help="Put this object or the folder", nargs=argparse.REMAINDER)
    parser.add_argument("--get", help="Get this object or the folder", nargs=argparse.REMAINDER)
    parser.add_argument("--delete", help="Remove this object or the folder", nargs=argparse.REMAINDER)

    parser.add_argument("--copy", help="Copy one object or folder to another store", nargs=argparse.REMAINDER)
    parser.add_argument("--move", help="Move this object or folder to another store", nargs=argparse.REMAINDER)
    parser.add_argument("--wget", help="Get the URL object", nargs=argparse.REMAINDER)

    parser.add_argument("--config", help="Configure this utility", nargs=argparse.REMAINDER)
    parser.add_argument("--store", help="Create and Show existing stores", nargs=argparse.REMAINDER)
    parser.add_argument("--meta", help="MetaData store configuration", nargs=argparse.REMAINDER)

    results = parser.parse_args()

    DEBUG_LEVEL = 5
    if results.debug != DEBUG_LEVEL:
        DEBUG_LEVEL = results.debug

    if DEBUG_LEVEL == 0:
        log_format = '%(color)s[%(levelname)1.1s %(asctime)s \
                %(module)s:%(lineno)d]%(end_color)s %(message)s'
        logfile = sys.argv[0] + ".log"
        logzero.logfile(logfile, maxBytes=1048576, backupCount=3, \
                        loglevel=logging.DEBUG, formatter=log_format)
        formatter = logzero.LogFormatter(fmt=log_format)
        logzero.setup_default_logger(level=logging.DEBUG, formatter=formatter)
    else:
        log_format = '%(message)s'
        formatter = logzero.LogFormatter(fmt=log_format)
        logzero.setup_default_logger(level=logging.INFO, formatter=formatter)

    recursive = results.r

    cfg_file = expanduser("~") + DEFAULT_CONFIG
    if not path.isfile(cfg_file) or not os.access(cfg_file, os.R_OK):
        logger.error(str("Unable to access " + cfg_file))
        sys.exit(2)
    with open(cfg_file, mode='r') as c_file:
        cfg_contents = c_file.read()
    cfg = EdgexConfig(cfg_contents)


    loop = asyncio.get_event_loop()

    if results.ls is not None:
        cmd = "ls"
        args = results.ls
        command(cmd, cfg, loop, args, recursive)
        sys.exit(0)

    if results.exists is not None:
        cmd = "exists"
        args = results.exists
        command(cmd, cfg, loop, args, recursive)
        sys.exit(0)

    if results.info is not None:
        cmd = "info"
        args = results.info
        command(cmd, cfg, loop, args, recursive)
        sys.exit(0)

    if results.put is not None:
        cmd = "put"
        args = results.put
        command(cmd, cfg, loop, args, recursive)
        sys.exit(0)

    if results.get is not None:
        cmd = "get"
        args = results.get
        command(cmd, cfg, loop, args, recursive)
        sys.exit(0)

    if results.delete is not None:
        cmd = "delete"
        args = results.delete
        command(cmd, cfg, loop, args, recursive)
        sys.exit(0)

    if results.copy is not None:
        cmd = "copy"
        args = results.copy
        command(cmd, cfg, loop, args, recursive)
        sys.exit(0)

    if results.move is not None:
        cmd = "move"
        args = results.move
        command(cmd, cfg, loop, args, recursive)
        sys.exit(0)

    if results.wget is not None:
        cmd = "wget"
        args = results.wget
        command(cmd, cfg, loop, args, recursive)
        sys.exit(0)

    if results.config is not None:
        cmd = "config"
        args = results.config
        command(cmd, cfg, loop, args, recursive)
        sys.exit(0)

    if results.store is not None:
        cmd = "store"
        args = results.store
        command(cmd, cfg, loop, args, recursive)
        sys.exit(0)

    if results.meta is not None:
        cmd = "meta"
        args = results.meta
        command(cmd, cfg, loop, args, recursive)
        sys.exit(0)

    parser.print_help()

if __name__ == "__main__":
    main()
